nginx:
  container_name: nginx2
  build: ./nginx
  ports:
    - "3000:80"
  volumes:
    - ./vue:/vue
    - ./nginx/log:/var/log/nginx
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    # - ./nginx/default.conf:/etc/nginx/sites-available/default.conf:ro
